/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cgg.arielgeometry.editor;

import com.cgg.arielgeometry.model.GeometryModel;
import com.cgg.arielgeometry.model.Shot;
import com.cgg.arielgeometry.model.io.ScannerMOOS;
import com.cgg.arielgeometry.model.io.UKOOAwriter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JFrame;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.cgg.arielgeometry.editor//ArielGeometryEditor//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "ArielGeometryEditorTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = true)
@ActionID(category = "Window", id = "com.cgg.arielgeometry.editor.ArielGeometryEditorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ArielGeometryEditorAction",
        preferredID = "ArielGeometryEditorTopComponent")
@Messages({
    "CTL_ArielGeometryEditorAction=ArielGeometryEditor",
    "CTL_ArielGeometryEditorTopComponent=ArielGeometryEditor Window",
    "HINT_ArielGeometryEditorTopComponent=This is a ArielGeometryEditor window"
})
public final class ArielGeometryEditorTopComponent extends TopComponent {

//    private ArielSpecialSourceRegularGeometryModel agm;
    private GeometryModel agm = null;
    private InstanceContent content = null;
    boolean debug = false;

    public ArielGeometryEditorTopComponent() {
//        agm = new ArielRegularGeometryModel();
        initComponents();
        setName(Bundle.CTL_ArielGeometryEditorTopComponent());
        setToolTipText(Bundle.HINT_ArielGeometryEditorTopComponent());
        content = new InstanceContent();
        associateLookup(new AbstractLookup(content));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        rlabel = new javax.swing.JLabel();
        slabel = new javax.swing.JLabel();
        rilslabel = new javax.swing.JLabel();
        rclslabel = new javax.swing.JLabel();
        rnbnlabel = new javax.swing.JLabel();
        silslabel = new javax.swing.JLabel();
        sclslabel = new javax.swing.JLabel();
        smxolabel = new javax.swing.JLabel();
        rils = new javax.swing.JTextField();
        rcls = new javax.swing.JTextField();
        rpl = new javax.swing.JTextField();
        sils = new javax.swing.JTextField();
        scls = new javax.swing.JTextField();
        sspl = new javax.swing.JTextField();
        StandardButton = new javax.swing.JButton();
        DefaultButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rls = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ssls = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bxs = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bys = new javax.swing.JTextField();
        MovingButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        speedx = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        speedy = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        spti = new javax.swing.JTextField();
        printtoggle = new javax.swing.JCheckBox();
        SpecialButton = new javax.swing.JButton();
        sboats = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        maxoffset = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        dbinsx = new javax.swing.JTextField();
        dbinsy = new javax.swing.JTextField();
        dnbnonemptybins = new javax.swing.JTextField();
        dmaxcov = new javax.swing.JTextField();
        davecov = new javax.swing.JTextField();
        dcovarea = new javax.swing.JTextField();
        dboatspeed = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        drecordingtime = new javax.swing.JTextField();
        loadfile = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        dtotaltraces = new javax.swing.JTextField();
        dtracedensity = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        dsnbs = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        rs = new javax.swing.JTextField();
        rss = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        shortoffset = new javax.swing.JTextField();
        backgroundImage = new javax.swing.JCheckBox();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel26, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel26.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(713, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel2);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jScrollPane2.TabConstraints.tabTitle"), jScrollPane2); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rlabel, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rlabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(slabel, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.slabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rilslabel, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rilslabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rclslabel, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rclslabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(rnbnlabel, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rnbnlabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(silslabel, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.silslabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sclslabel, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.sclslabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(smxolabel, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.smxolabel.text")); // NOI18N

        rils.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rils.text")); // NOI18N
        rils.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rilsActionPerformed(evt);
            }
        });

        rcls.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rcls.text")); // NOI18N

        rpl.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rpl.text")); // NOI18N

        sils.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.sils.text")); // NOI18N

        scls.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.scls.text")); // NOI18N

        sspl.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.sspl.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(StandardButton, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.StandardButton.text")); // NOI18N
        StandardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandardButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(DefaultButton, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.DefaultButton.text")); // NOI18N
        DefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefaultButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel1.text")); // NOI18N

        rls.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rls.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel2.text")); // NOI18N

        ssls.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.ssls.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel4.text")); // NOI18N

        bxs.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.bxs.text")); // NOI18N
        bxs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxsActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel5.text")); // NOI18N

        bys.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.bys.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(MovingButton, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.MovingButton.text")); // NOI18N
        MovingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovingButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel6.text")); // NOI18N

        speedx.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.speedx.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel8.text")); // NOI18N

        speedy.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.speedy.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel9.text")); // NOI18N

        spti.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.spti.text")); // NOI18N
        spti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sptiActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(printtoggle, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.printtoggle.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(SpecialButton, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.SpecialButton.text")); // NOI18N
        SpecialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpecialButtonActionPerformed(evt);
            }
        });

        sboats.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.sboats.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel10.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel11.text")); // NOI18N

        maxoffset.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.maxoffset.text")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel12.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel13, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel13.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel14, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel14.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel15, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel15.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel16, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel16.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel17, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel17.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel18, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel18.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel19, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel19.text")); // NOI18N

        dbinsx.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.dbinsx.text")); // NOI18N
        dbinsx.setPreferredSize(new java.awt.Dimension(70, 20));

        dbinsy.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.dbinsy.text")); // NOI18N

        dnbnonemptybins.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.dnbnonemptybins.text")); // NOI18N
        dnbnonemptybins.setPreferredSize(new java.awt.Dimension(70, 20));

        dmaxcov.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.dmaxcov.text")); // NOI18N
        dmaxcov.setPreferredSize(new java.awt.Dimension(70, 20));

        davecov.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.davecov.text")); // NOI18N
        davecov.setPreferredSize(new java.awt.Dimension(70, 20));

        dcovarea.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.dcovarea.text")); // NOI18N
        dcovarea.setPreferredSize(new java.awt.Dimension(70, 20));

        dboatspeed.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.dboatspeed.text")); // NOI18N
        dboatspeed.setPreferredSize(new java.awt.Dimension(70, 20));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel20, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel20.text")); // NOI18N

        drecordingtime.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.drecordingtime.text")); // NOI18N
        drecordingtime.setPreferredSize(new java.awt.Dimension(70, 20));

        org.openide.awt.Mnemonics.setLocalizedText(loadfile, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.loadfile.text")); // NOI18N
        loadfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadfileActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel21, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel21.text")); // NOI18N

        dtotaltraces.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.dtotaltraces.text")); // NOI18N

        dtracedensity.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.dtracedensity.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel22, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel22.text")); // NOI18N

        dsnbs.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.dsnbs.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel23, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel23.text")); // NOI18N

        rs.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rs.text")); // NOI18N

        rss.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rss.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel24, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel24.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel25, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel25.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel27, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel27.text")); // NOI18N

        shortoffset.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.shortoffset.text")); // NOI18N

        backgroundImage.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(backgroundImage, org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.backgroundImage.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(backgroundImage))
                .addContainerGap(441, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(StandardButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(MovingButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(SpecialButton)
                                    .addGap(4, 4, 4)
                                    .addComponent(loadfile)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DefaultButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                    .addComponent(printtoggle))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rclslabel)
                                        .addComponent(rilslabel)
                                        .addComponent(rnbnlabel)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(rlabel)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel24)
                                        .addComponent(jLabel25))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rss, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rpl)
                                        .addComponent(rcls, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rils, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rls)
                                        .addComponent(bxs)
                                        .addComponent(bys)
                                        .addComponent(maxoffset)
                                        .addComponent(rs)
                                        .addComponent(shortoffset))
                                    .addGap(50, 50, 50)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(silslabel)
                                                .addComponent(slabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(sils, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(sclslabel)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(1, 1, 1)
                                                    .addComponent(smxolabel))
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel6)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel10))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(sspl)
                                                .addComponent(scls)
                                                .addComponent(ssls)
                                                .addComponent(speedx)
                                                .addComponent(speedy)
                                                .addComponent(spti)
                                                .addComponent(sboats, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGap(106, 106, 106))
                        .addComponent(jSeparator1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(186, 186, 186)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel23))
                                    .addGap(36, 36, 36)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dsnbs)
                                        .addComponent(dtracedensity)
                                        .addComponent(dcovarea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(davecov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dmaxcov, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dnbnonemptybins, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dbinsx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dbinsy, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(drecordingtime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dboatspeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dtotaltraces, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backgroundImage)
                .addContainerGap(404, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rlabel)
                        .addComponent(slabel))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rilslabel)
                        .addComponent(silslabel)
                        .addComponent(rils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sils, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rclslabel)
                        .addComponent(sclslabel)
                        .addComponent(rcls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rnbnlabel)
                        .addComponent(smxolabel)
                        .addComponent(rpl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sspl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(rls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(ssls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(sboats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addGap(4, 4, 4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel25))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(bxs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(speedx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(bys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(speedy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(spti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(maxoffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(shortoffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(57, 57, 57)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dbinsx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dbinsy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dsnbs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dtotaltraces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dnbnonemptybins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dmaxcov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(davecov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dcovarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dtracedensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dboatspeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(drecordingtime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(StandardButton)
                        .addComponent(DefaultButton)
                        .addComponent(MovingButton)
                        .addComponent(printtoggle)
                        .addComponent(SpecialButton)
                        .addComponent(loadfile))
                    .addContainerGap()))
        );

        jLabel2.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jLabel2.AccessibleContext.accessibleName")); // NOI18N

        jScrollPane1.setViewportView(jPanel1);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.jScrollPane1.TabConstraints.tabTitle"), jScrollPane1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadfileActionPerformed
        //        agm = new GeometryModel("ReceiverModel", "EmptyShotModel");
        if(agm != null) {
            content.remove(agm);
        }
        agm = new GeometryModel("FileReceiverModel", "FileShotModel");
        storeUserGeometryValues();
        Shot.timezero = 0;
        Shot.shottimeinterval = 10;
        Shot.dailystarttime = 7 * 3600;
        Shot.dailyendtime = 17 * 3600;

        dowork();
    }//GEN-LAST:event_loadfileActionPerformed

    private void SpecialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpecialButtonActionPerformed
        agm = new GeometryModel("OffsetSyntheticDriftReceiverModel", "ReverseUserDefinedShotModel");
        dowork();
        //        UKOOAwriter writer = new UKOOAwriter(agm, "C:\\Users\\jgrimsdale\\Desktop\\ukooatest.p190");
        //        writer.write();
    }//GEN-LAST:event_SpecialButtonActionPerformed

    private void sptiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sptiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sptiActionPerformed

    private void MovingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovingButtonActionPerformed
        agm = new GeometryModel("ConstantDriftReceiverModel", "MovingShotModel");
        dowork();
    }//GEN-LAST:event_MovingButtonActionPerformed

    private void bxsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bxsActionPerformed

    private void DefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefaultButtonActionPerformed
        resetDefaultGeometryValues();
    }//GEN-LAST:event_DefaultButtonActionPerformed

    private void StandardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandardButtonActionPerformed
        agm = new GeometryModel("ReceiverModel", "ShotModel");
        dowork();
    }//GEN-LAST:event_StandardButtonActionPerformed

    private void rilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rilsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rilsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DefaultButton;
    private javax.swing.JButton MovingButton;
    private javax.swing.JButton SpecialButton;
    private javax.swing.JButton StandardButton;
    private javax.swing.JCheckBox backgroundImage;
    private javax.swing.JTextField bxs;
    private javax.swing.JTextField bys;
    private javax.swing.JTextField davecov;
    private javax.swing.JTextField dbinsx;
    private javax.swing.JTextField dbinsy;
    private javax.swing.JTextField dboatspeed;
    private javax.swing.JTextField dcovarea;
    private javax.swing.JTextField dmaxcov;
    private javax.swing.JTextField dnbnonemptybins;
    private javax.swing.JTextField drecordingtime;
    private javax.swing.JTextField dsnbs;
    private javax.swing.JTextField dtotaltraces;
    private javax.swing.JTextField dtracedensity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton loadfile;
    private javax.swing.JTextField maxoffset;
    private javax.swing.JCheckBox printtoggle;
    private javax.swing.JTextField rcls;
    private javax.swing.JLabel rclslabel;
    private javax.swing.JTextField rils;
    private javax.swing.JLabel rilslabel;
    private javax.swing.JLabel rlabel;
    private javax.swing.JTextField rls;
    private javax.swing.JLabel rnbnlabel;
    private javax.swing.JTextField rpl;
    private javax.swing.JTextField rs;
    private javax.swing.JTextField rss;
    private javax.swing.JTextField sboats;
    private javax.swing.JTextField scls;
    private javax.swing.JLabel sclslabel;
    private javax.swing.JTextField shortoffset;
    private javax.swing.JTextField sils;
    private javax.swing.JLabel silslabel;
    private javax.swing.JLabel slabel;
    private javax.swing.JLabel smxolabel;
    private javax.swing.JTextField speedx;
    private javax.swing.JTextField speedy;
    private javax.swing.JTextField spti;
    private javax.swing.JTextField ssls;
    private javax.swing.JTextField sspl;
    // End of variables declaration//GEN-END:variables

    private void dowork() {
        storeUserGeometryValues();
        printUserGeometryValues();
        agm.calculate();
        if (printtoggle.isSelected()) {
            agm.printbindetails();
        }
        updatecalculatedvalues();
        content.add(agm);
        System.out.printf("End of run\n\n");
    }

    private void storeUserGeometryValues() {
        agm.setSILS(new Float(sils.getText()));
        agm.setSCLS(new Float(scls.getText()));
        agm.setSSPL(new Integer(sspl.getText()));
        agm.setSSLS(new Integer(ssls.getText()));
        agm.setBXS(new Float(bxs.getText()));
        agm.setBXY(new Float(bys.getText()));
        agm.setMAXOFFSET(new Float(maxoffset.getText()));
        agm.setRILS(new Float(rils.getText()));
        agm.setRCLS(new Float(rcls.getText()));
        agm.setRPL(new Integer(rpl.getText()));
        agm.setRLS(new Integer(rls.getText()));
        agm.cspeedx = new Float(speedx.getText());
        agm.cspeedy = new Float(speedy.getText());
        agm.spti = new Float(spti.getText());
        agm.sboats = new Integer(sboats.getText());
        agm.rs = new Integer(rs.getText());
        agm.rss = new Float(rss.getText());
        agm.shortoffset = new Float(shortoffset.getText());
        agm.backgroundimagedisplayed = backgroundImage.isSelected();
    }

    private void updatecalculatedvalues() {
        dbinsx.setText(String.format("%d", agm.binsx));
        dbinsy.setText(String.format("%d", agm.binsy));
        dsnbs.setText(String.format("%d", agm.snbs));
        dboatspeed.setText(String.format("%9.4f", agm.boatspeed));
        dcovarea.setText(String.format("%9.4f", agm.covarea));
        dmaxcov.setText(String.format("%d", agm.covmax));
        davecov.setText(String.format("%9.4f", agm.covave));
        dnbnonemptybins.setText(String.format("%d", agm.nbnonemptybins));
        drecordingtime.setText(String.format("%9.4f", agm.recordingtime));
        dtotaltraces.setText(String.format("%d", agm.totaltraces));
        dtracedensity.setText(String.format("%9.4f", agm.tracedensity));
        if (agm.rbl != null && agm.rtr != null && agm.sbl != null) {
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues rnbn=%d\n", agm.rnbn);
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues rnbpos=%d\n", agm.rnbpos);
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues rpwh=%f\n", agm.rpwh);
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues rbl.x=%f rbl.y=%f\n", agm.rbl.x, agm.rbl.y);
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues rtr.x=%f rtr.y=%f\n", agm.rtr.x, agm.rtr.y);
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues rstartswh=%f\n", agm.rstartswh);
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues rendsw=%f\n", agm.rendswh);
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues snbs=%d\n", agm.snbs);
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues spwh=%f\n", agm.spwh);
            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues spht=%f\n", agm.spht);

            System.out.printf("GeometryEditorTopComponent.updatecalculatedvalues sbl.x=%f sbl.y=%f\n", agm.sbl.x, agm.sbl.y);
        }
    }

    private void resetDefaultGeometryValues() {
        rils.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rils.text")); // NOI18N
        rcls.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rcls.text")); // NOI18N
        rpl.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rpl.text")); // NOI18N
        sils.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.sils.text")); // NOI18N
        scls.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.scls.text")); // NOI18N
        sspl.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.sspl.text")); // NOI18N
        rls.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.rls.text")); // NOI18N
        ssls.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.ssls.text")); // NOI18N
        bxs.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.bxs.text")); // NOI18N
        bys.setText(org.openide.util.NbBundle.getMessage(ArielGeometryEditorTopComponent.class, "ArielGeometryEditorTopComponent.bys.text")); // NOI18N
    }

    private void printUserGeometryValues() {
        System.out.println("GeometryEditorTopComponent.printGeometryValues rils = " + rils.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues rcls = " + rcls.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues rpl = " + rpl.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues rls = " + rls.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues sils = " + sils.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues scls = " + scls.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues sspl = " + sspl.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues ssls = " + ssls.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues bxs = " + bxs.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues bys = " + bys.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues spti = " + spti.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues sboats = " + sboats.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues cspeedx = " + speedx.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues cspeedy = " + speedy.getText());
        System.out.println("GeometryEditorTopComponent.printGeometryValues maxoffset = " + maxoffset.getText());
        System.out.println("");
    }

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
