/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cgg.arielgeometry.viewer;

import com.cgg.arielgeometry.model.AbstractArielGeometryModel;
import java.awt.BorderLayout;
import java.util.Collection;
import javax.swing.JPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.cgg.arielgeometry.viewer//ArielGeometryViewer//EN",
        autostore = false)
@TopComponent.Description(
        preferredID = "ArielGeometryViewerTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "com.cgg.arielgeometry.viewer.ArielGeometryViewerTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_ArielGeometryViewerAction",
        preferredID = "ArielGeometryViewerTopComponent")
@Messages({
    "CTL_ArielGeometryViewerAction=ArielGeometryViewer",
    "CTL_ArielGeometryViewerTopComponent=ArielGeometryViewer Window",
    "HINT_ArielGeometryViewerTopComponent=This is an ArielGeometryViewer window"
})
public final class ArielGeometryViewerTopComponent extends TopComponent implements LookupListener {

    private org.openide.util.Lookup.Result<AbstractArielGeometryModel> result;
    private JPanel canvasPanel = new JPanel();
    private ArielGeometryViewPanel agvp = new ArielGeometryViewPanel();
    
    public ArielGeometryViewerTopComponent() {
        initComponents();
        setName(Bundle.CTL_ArielGeometryViewerTopComponent());
        setToolTipText(Bundle.HINT_ArielGeometryViewerTopComponent());
        this.setLayout(new BorderLayout());
        canvasPanel.setLayout(new BorderLayout());
        canvasPanel.add(agvp.getCanvas());
        this.add(canvasPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        result = org.openide.util.Utilities.actionsGlobalContext().lookupResult(AbstractArielGeometryModel.class);
        result.addLookupListener(this);
    }

    @Override
    public void componentClosed() {
        result.removeLookupListener(this);
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public void resultChanged(LookupEvent le) {
        Collection<? extends AbstractArielGeometryModel> allagms = result.allInstances();
        System.out.println("In resultChanged of ArielGeometryViewerTopComponent");

        for(AbstractArielGeometryModel agm : allagms) {
            agvp.drawmap(agm);
        }
    }
}
