/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cgg.arielplot;

import com.cgg.arielgeometrycurrents.TideModel;
import java.awt.BorderLayout;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYDataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author jgrimsdale
 */
public class PlotJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlotJPanel
     */
    public PlotJPanel(String title, TideModel tm) {
        initComponents();
        setToolTipText(title);
        setVisible(true);
    }

    public void drawchart() {
        System.out.println("drawchart");
    }

    public void drawXYLineChart(double data[][]) {
        System.out.println("drawXYLineChart");
        XYDataset xyd = createXYSeriesDataSet(data);
        JFreeChart jfc = ChartFactory.createXYLineChart(
                "FFT",
                "Freq",
                "Amplitude",
                xyd,
                PlotOrientation.VERTICAL, true, true, false);
        XYPlot xyplot = (XYPlot)jfc.getPlot();
        xyplot.setDomainPannable(true);
        xyplot.setRangePannable(true);
        ChartPanel chartPanel = new ChartPanel(jfc);
        chartPanel.setFillZoomRectangle(true);
        chartPanel.setMouseWheelEnabled(true);
//      Dell laptop screen
//        chartPanel.setPreferredSize(new Dimension(600, 300));
//      Dell large screen
//        chartPanel.setPreferredSize(new Dimension(700, 500));
//      smart screen
//        chartPanel.setPreferredSize(new Dimension(400, 300));
        chartPanel.setMouseZoomable(true, false);
        chartPanel.setRangeZoomable(true);
        chartPanel.setDomainZoomable(true);
        chartPanel.setZoomAroundAnchor(true);
//        setLayout(new GridLayout(2, 2));
        setLayout(new BorderLayout());
        add(chartPanel);
        setVisible(true);
    }

    public XYDataset createXYSeriesDataSet(double data[][]) {
        int x = data.length;
        int y = data[0].length;
        XYSeries series = new XYSeries("Tide");
        XYDataset xyd = new XYSeriesCollection(series);
        for (int i = 0; i < y; i++) {
            series.add(data[0][i], data[1][i]);
        }
        return xyd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
